In [1]:
import math
def sigmoid(x):
    return 1 / (1+math.exp(-x))

In [3]:
sigmoid(100)

1.0

In [6]:
math.floor(sigmoid(-123))

0

In [7]:
def tanh(x):
    return (math.exp(x)-math.exp(-x))/(math.exp(x)+math.exp(-x))

In [8]:
tanh(-56)

-1.0

In [9]:
tanh(688)

1.0

In [10]:
# tanh(-1,1) #sigmoid(0,1)

In [11]:
def reLU(x):
    return max(0,x)

In [12]:
reLU(-80)

0

In [13]:
def LeakyreLU(x):
    return max(0.1*x,x)

In [14]:
LeakyreLU(-100)

-10.0

In [15]:
#most likely using redimate api from tf or keras

In [16]:
import numpy as np
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [18]:
profit=revenue-expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [19]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [20]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])