<a href="https://colab.research.google.com/github/snmath-pi/TensorFlow/blob/main/TensorFlowIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
# tensor: vector and matrices generalised to higher dimension
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)

In [ ]:
rank1_tensor = tf.Variable(["Test", "Ok"], tf.string)
rank2_tensor = tf.Variable([['Test'], ['ok'], ['watermelon']], tf.string)
tf.rank(rank2_tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
rank2_tensor.shape

TensorShape([3, 1])

In [ ]:
tensor1 = tf.ones([1, 2, 3])
print(tensor1)
tensor2 = tf.reshape(tensor1, [2, 3,1])
print(tensor2)
tensor3 = tf.reshape(tensor1, [3, -1]) # -1 determines what should be there if valid
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
t = tf.zeros([5, 5, 5, 5])
print(t)
t = tf.reshape(t, [625])
print(t)